export const BOARD = [
  "Go",
  "Gdynia",
  "Chest",
  "Taipei",
  "Income Tax",
  "Monopoly Rail",
  "Tokyo",
  "Chance",
  "Barcelona",
  "Athens",
  "Jail",
  "Istambul",
  "Solar Energy",
  "Kiev",
  "Toronto",
  "Monopoly Air",
  "Rome",
  "Chest",
  "Shanghai",
  "Vancouver",
  "Parking",
  "Sydney",
  "Chance",
  "New York",
  "London",
  "Monopoly Cruise",
  "Beijing",
  "Hong Kong",
  "Wind Energy",
  "Jerusalem",
  "Go To Jail",
  "Paris",
  "Belgrade",
  "Chest",
  "Cape Town",
  "Monopoly Space",
  "Chance",
  "Riga",
  "Super Tax",
  "Montreal",
] as const;
export type Place = typeof BOARD[number];
